.TH ORLOK "1" "November 2025" "Jacob Niemeir" "User Commands"
.SH NAME
Orlok \- a process tracer
.SH SYNOPSIS
.B orlok [-p \fI\,PID\/\fR]

.SH DESCRIPTION
.TP
\fB\-h\fR 
display program usage
.TP
\fB\-p[PID]\fR 
process ID of the process to hook

.SH COPYRIGHT
Copyright \(co 2025 Jacob Niemeir.
.br
Licensed under the GPL V2