.TH ORLOK "1" "November 2025" "Jacob Niemeir" "User Commands"
.SH NAME
Orlok \- A basic strace-like process tracing utility for x86_64 systems, created for educational purposes.
.SH SYNOPSIS
.B orlok [-n \fI\,PATH\/\fR] | [-p \fI\,PID\/\fR]

.SH DESCRIPTION
.TP
\fB\-h\fR 
Display program usage
.TP
\fB\-n\fR 
Specify path of executable to run
.TP
\fB\-p[PID]\fR 
Specify PID of the process to hook

.SH COPYRIGHT
Copyright \(co 2025 Jacob Niemeir.
.br
Licensed under the GPL V2